'use strict';

/**
 * @ngdoc function
 * @name emploiDuTempsApp.controller:CarousselprofilCtrl
 * @description
 * # CarousselprofilCtrl
 * Controller of the emploiDuTempsApp
 */
angular.module('emploiDuTempsApp')
    .controller('carousselProfilCtrl', ['$scope', 'ConceptionEdtService', '$modal', function ($scope, ConceptionEdtService, $modal) {
        //debugger;
        this.message = 'Hello, I am testing';
        //Index des carousel
        $scope.index0=0;
        $scope.index1=1;
        $scope.index2=2;
        $scope.index3=3;
        $scope.index4=4;
        $scope.index5=5;
        $scope.slideIndex = $scope.index0;
        //
        $scope.profil = ConceptionEdtService.getUvProfil();
        $scope.uvs = [];
        $scope.myUvs = [];
        $scope.hours = [
            {heure: ''},
            {heure: '8'},
            {heure: '9'},
            {heure: '10'},
            {heure: '11'},
            {heure: '12'},
            {heure: '13'},
            {heure: '14'},
            {heure: '15'},
            {heure: '16'},
            {heure: '17'},
            {heure: '18'},
            {heure: '19'}
        ];
        $scope.myISI = [
            {UV: 'IF07', Lundi: [
                {h: ''},
                {h: ''},
                {h: 'C104', bgcolor: '#FD91A6'},
                {h: 'C104', bgcolor: '#FD91A6'},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: 'A106', bgcolor: '#B4FBAC'},
                    {h: 'A106', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'IF09', Lundi: [
                {h: 'S102', bgcolor: '#FD91A6'},
                {h: 'S102', bgcolor: '#FD91A6'},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: 'A203', bgcolor: '#B4FBAC'},
                {h: 'A203', bgcolor: '#B4FBAC'},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'IF14', Lundi: [
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: 'P201', bgcolor: '#B4FBAC'},
                    {h: 'P201', bgcolor: '#B4FBAC'},
                    {h: 'S103', bgcolor: '#B4FBAC'},
                    {h: 'S103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'P101', bgcolor: '#B4FBAC'},
                    {h: 'P101', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'B101', bgcolor: '#B4FBAC'},
                    {h: 'B101', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: 'B101', bgcolor: '#FD91A6'},
                    {h: 'B101', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'LO01', Lundi: [
                {h: ''},
                {h: ''},
                {h: 'B209', bgcolor: '#B4FBAC'},
                {h: 'B209', bgcolor: '#B4FBAC'},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: 'A208', bgcolor: '#F9FB93'}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A208', bgcolor: '#B0B268'},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: 'A208', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: 'B101', bgcolor: '#FD91A6'},
                    {h: 'B101', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A208', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'LO02', Lundi: [
                {h: ''},
                {h: ''},
                {h: 'P101', bgcolor: '#B4FBAC'},
                {h: 'P101', bgcolor: '#B4FBAC'},
                {h: ''},
                {h: ''},
                {h: 'P204', bgcolor: '#B4FBAC'},
                {h: 'P204', bgcolor: '#B4FBAC'},
                {h: 'M204', bgcolor: '#B4FBAC'},
                {h: 'M204', bgcolor: '#B4FBAC'},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: 'P204', bgcolor: '#B4FBAC'},
                    {h: 'P204', bgcolor: '#B4FBAC'},
                    {h: 'P204', bgcolor: '#F9FB93'},
                    {h: 'P204', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'P204', bgcolor: '#F9FB93'},
                    {h: 'P204', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: 'P204', bgcolor: '#F9FB93'},
                    {h: 'P204', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'P204', bgcolor: '#B4FBAC'},
                    {h: 'P204', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: 'N101', bgcolor: '#FD91A6'},
                    {h: 'N101', bgcolor: '#FD91A6'},
                    {h: '--', bgcolor: '#B0B268'},
                    {h: '--', bgcolor: '#B0B268'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'P204', bgcolor: '#B4FBAC'},
                    {h: 'P204', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: 'P204', bgcolor: '#B4FBAC'},
                    {h: 'P204', bgcolor: '#B4FBAC'},
                    {h: 'P204', bgcolor: '#F9FB93'},
                    {h: 'P204', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'NF16', Lundi: [
                {h: ''},
                {h: ''},
                {h: 'B203', bgcolor: '#B4FBAC'},
                {h: 'B203', bgcolor: '#B4FBAC'},
                {h: ''},
                {h: ''},
                {h: 'B207', bgcolor: '#B4FBAC'},
                {h: 'B207', bgcolor: '#B4FBAC'},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: 'A105', bgcolor: '#B4FBAC'},
                    {h: 'A105', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: 'A105', bgcolor: '#B4FBAC'},
                    {h: 'A105', bgcolor: '#B4FBAC'},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: 'A212', bgcolor: '#F9FB93'}
                ],
                Jeudi: [
                    {h: '--', bgcolor: '#81B47B'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: 'A001', bgcolor: '#FD91A6'},
                    {h: 'A001', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: 'A212', bgcolor: '#F9FB93'},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: 'A105', bgcolor: '#B4FBAC'},
                    {h: 'A105', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A105', bgcolor: '#B4FBAC'},
                    {h: 'A105', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: '--', bgcolor: '#B0B268'},
                    {h: '--', bgcolor: '#B0B268'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'NF20', Lundi: [
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: '--', bgcolor: '#81B47B'},
                {h: '--', bgcolor: '#81B47B'},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'B202', bgcolor: '#B4FBAC'},
                    {h: 'B202', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'P102', bgcolor: '#B4FBAC'},
                    {h: 'P102', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'C001', bgcolor: '#FD91A6'},
                    {h: 'C001', bgcolor: '#FD91A6'},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'RE01', Lundi: [
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'S104', bgcolor: '#B4FBAC'},
                    {h: 'S104', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: 'S103', bgcolor: '#B4FBAC'},
                    {h: 'S103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'S202', bgcolor: '#B4FBAC'},
                    {h: 'S202', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: 'A002', bgcolor: '#FD91A6'},
                    {h: 'A002', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'SY01', Lundi: [
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A001', bgcolor: '#FD91A6'},
                    {h: 'A001', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: 'B203', bgcolor: '#B4FBAC'},
                    {h: 'B203', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: 'B204', bgcolor: '#B4FBAC'},
                    {h: 'B204', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: 'B204', bgcolor: '#B4FBAC'},
                    {h: 'B204', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'SY02', Lundi: [
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: 'A206', bgcolor: '#F9FB93'},
                {h: 'A206', bgcolor: '#F9FB93'},
                {h: '--', bgcolor: '#81B47B'},
                {h: '--', bgcolor: '#81B47B'},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: 'A206', bgcolor: '#B0B268'},
                    {h: 'A206', bgcolor: '#B0B268'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: 'A205', bgcolor: '#F9FB93'},
                    {h: 'A205', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: 'A001', bgcolor: '#FD91A6'},
                    {h: 'A001', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'B204', bgcolor: '#B4FBAC'},
                    {h: 'B204', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: 'A206', bgcolor: '#B0B268'},
                    {h: 'A206', bgcolor: '#B0B268'},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: 'A206', bgcolor: '#F9FB93'},
                    {h: 'A206', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]}
        ];
        $scope.mySM = [
            {UV: 'CS03', Lundi: [
                {h: 'M500', bgcolor: '#FD91A6'},
                {h: 'M500', bgcolor: '#FD91A6'},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: 'A103', bgcolor: '#B4FBAC'},
                {h: 'A103', bgcolor: '#B4FBAC'},
                {h: 'A103', bgcolor: '#B4FBAC'},
                {h: 'A103', bgcolor: '#B4FBAC'},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: 'A103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'LO01', Lundi: [
                {h: ''},
                {h: ''},
                {h: 'B209', bgcolor: '#B4FBAC'},
                {h: 'B209', bgcolor: '#B4FBAC'},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: 'A208', bgcolor: '#F9FB93'}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A208', bgcolor: '#B0B268'},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: 'A208', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: 'B101', bgcolor: '#FD91A6'},
                    {h: 'B101', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A208', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'MQ01', Lundi: [
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: '--', bgcolor: '#B0B268'},
                {h: '--', bgcolor: '#B0B268'},
                {h: 'J003', bgcolor: '#F9FB93'},
                {h: 'J003', bgcolor: '#F9FB93'},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: 'A002', bgcolor: '#FD91A6'},
                    {h: 'A002', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: 'B209', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'S201', bgcolor: '#B4FBAC'},
                    {h: 'S201', bgcolor: '#B4FBAC'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: ''}
                ],
                Vendredi: [
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: 'B207', bgcolor: '#B4FBAC'},
                    {h: 'B207', bgcolor: '#B4FBAC'},
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: 'J003', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'MQ03', Lundi: [
                {h: 'A108', bgcolor: '#B4FBAC'},
                {h: 'A108', bgcolor: '#B4FBAC'},
                {h: '--', bgcolor: '#81B47B'},
                {h: '--', bgcolor: '#81B47B'},
                {h: ''},
                {h: ''},
                {h: '--', bgcolor: '#999999'},
                {h: '--', bgcolor: '#999999'},
                {h: '--', bgcolor: '#999999'},
                {h: '--', bgcolor: '#999999'},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: '--', bgcolor: '#999999'},
                    {h: '--', bgcolor: '#999999'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: 'C002', bgcolor: '#FD91A6'},
                    {h: 'C002', bgcolor: '#FD91A6'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: '--', bgcolor: '#81B47B'},
                    {h: ''},
                    {h: ''},
                    {h: '--', bgcolor: '#B0B268'},
                    {h: '--', bgcolor: '#B0B268'},
                    {h: 'S104', bgcolor: '#B4FBAC'},
                    {h: 'S104', bgcolor: '#B4FBAC'},
                    {h: 'A108', bgcolor: '#B4FBAC'},
                    {h: 'A108', bgcolor: '#B4FBAC'}
                ],
                Jeudi: [
                    {h: 'S204', bgcolor: '#B4FBAC'},
                    {h: 'S204', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: 'J006', bgcolor: '#B0B268'},
                    {h: 'J006', bgcolor: '#B0B268'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'J006', bgcolor: '#F9FB93'},
                    {h: 'J006', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'MQ07', Lundi: [
                {h: ''},
                {h: ''},
                {h: 'B210', bgcolor: '#B4FBAC'},
                {h: 'B210', bgcolor: '#B4FBAC'},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: 'D101', bgcolor: '#F9FB93'}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: 'B210', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: 'D101', bgcolor: '#F9FB93'}
                ],
                Samedi: [
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: 'D101', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'MT11', Lundi: [
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: 'S102', bgcolor: '#B4FBAC'},
                    {h: 'S102', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'S102', bgcolor: '#B4FBAC'},
                    {h: 'S102', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'MT13', Lundi: [
                {h: ''},
                {h: ''},
                {h: 'A205', bgcolor: '#F9FB93'},
                {h: 'A205', bgcolor: '#F9FB93'},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: 'B103', bgcolor: '#B4FBAC'},
                    {h: 'B103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: 'B101', bgcolor: '#FD91A6'},
                    {h: 'B101', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'TN14', Lundi: [
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: 'A201', bgcolor: '#F9FB93'},
                {h: 'A201', bgcolor: '#F9FB93'},
                {h: 'A201', bgcolor: '#F9FB93'},
                {h: 'A201', bgcolor: '#F9FB93'},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'P103', bgcolor: '#B4FBAC'},
                    {h: 'P103', bgcolor: '#B4FBAC'},
                    {h: 'P103', bgcolor: '#B4FBAC'},
                    {h: 'P103', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'P103', bgcolor: '#B4FBAC'},
                    {h: 'P103', bgcolor: '#B4FBAC'},
                    {h: 'P103', bgcolor: '#B4FBAC'},
                    {h: 'P103', bgcolor: '#B4FBAC'}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: 'A002', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'A201', bgcolor: '#F9FB93'},
                    {h: 'A201', bgcolor: '#F9FB93'},
                    {h: 'A201', bgcolor: '#F9FB93'},
                    {h: 'A201', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: 'P203', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]},
            {UV: 'TN15', Lundi: [
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''},
                {h: ''}
            ],
                Mardi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Mercredi: [
                    {h: ''},
                    {h: ''},
                    {h: 'S204', bgcolor: '#FD91A6'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'IUT1', bgcolor: '#F9FB93'},
                    {h: 'IUT1', bgcolor: '#F9FB93'},
                    {h: 'IUT1', bgcolor: '#F9FB93'},
                    {h: 'IUT1', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''}
                ],
                Jeudi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: 'IUT1', bgcolor: '#F9FB93'},
                    {h: 'IUT1', bgcolor: '#F9FB93'},
                    {h: 'IUT1', bgcolor: '#F9FB93'},
                    {h: 'IUT1', bgcolor: '#F9FB93'},
                    {h: ''},
                    {h: ''}
                ],
                Vendredi: [
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ],
                Samedi: [
                    {h: 'S203', bgcolor: '#B4FBAC'},
                    {h: 'S203', bgcolor: '#B4FBAC'},
                    {h: 'S203', bgcolor: '#B4FBAC'},
                    {h: 'S203', bgcolor: '#B4FBAC'},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''},
                    {h: ''}
                ]}
        ];

        //$scope.uvs = $scope.myISI;
        if ($scope.profil.value === 'ISI') {
            $scope.uvs = $scope.myISI;
            $scope.myUvs = $scope.myISI.UV;
        } else if ($scope.profil.value === 'SM') {
            $scope.uvs = $scope.mySM;
            $scope.myUvs = $scope.mySM.UV;
        } else {
            $scope.uvs = [];
            window.alert('Option pas encore implémentée');
        }
        console.log('@Profil de Formation');
        $scope.sortableOptions = {
            dropOnEmpty: true,
            placeholder: 'placeholder',
            connectWith: '.td'
        };
        $scope.awesomeThings = [
            'HTML5 Boilerplate',
            'AngularJS',
            'Karma'
        ];
        $scope.dropped = function (dragEl, dropEl) { // function referenced by the drop target
            //this is application logic, for the demo we just want to color the grid squares
            //the directive provides a native dom object, wrap with jqlite
            var drop = angular.element(dropEl);
            var drag = angular.element(dragEl);

            //clear the previously applied color, if it exists
            var bgClass = drop.attr('data-color');
            if (bgClass) {
                drop.removeClass(bgClass);
            }

            //add the dragged color
            bgClass = drag.attr("data-color");
            drop.addClass(bgClass);
            drop.attr('data-color', bgClass);

            //if element has been dragged from the grid, clear dragged color
            if (drag.attr("x-lvl-drop-target")) {
                drag.removeClass(bgClass);
            }
        }

        $scope.dropCallback = function (h, $index) {
            //if ($scope.uvs.map(function(item) { return item.title; }).join('') === 'GOLLUM') {
            //    $scope.uvs.forEach(function(value, key) { $scope.list3[key].drag = false; });
            //}
            window.alert('Hello, on peut y ajouter une action (^_^)');
        };

        $scope.lancerTest = function () {
            window.alert('Je teste mes Uvs (°_°)');
        };
        $scope.detailView = function (uv, salle, index) {
            ConceptionEdtService.setUv(uv);
            ConceptionEdtService.setLaSalle(salle);
            ConceptionEdtService.setHoraireIndex(index);
            if (salle === '--') {
                //Do nothing
            } else {
                var modalInstance = $modal.open({
                    templateUrl: 'views/partial/detailsalle.html',
                    controller: 'DetailsalleCtrl',
                    windowClass: 'app-modal-window'
                    //, size: 'lg'
                });
                $log.info('modal opened');
                modalInstance.result.then(function () {
                    $log.info($scope.selected);
                }, function () {
                    $log.info('Modal dismissed at: ' + new Date());
                });
            }
        };

        $scope.slideer = function(index) {
            $scope.slideIndex = index;
            window.alert($scope.slideIndex);
        };
    }]);